# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 00:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=4000)),
                ('lastUpdate', models.DateTimeField(auto_now=True, verbose_name='last update')),
            ],
        ),
        migrations.CreateModel(
            name='Crossing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(verbose_name='active?')),
                ('bicycleCrossing', models.BooleanField(verbose_name='bicycle crossing')),
                ('country1', models.CharField(choices=[('AL', 'Albania'), ('AU', 'Austria'), ('BH', 'Bosnia Herzegovina'), ('BU', 'Bulgaria'), ('CR', 'Croatia'), ('GR', 'Greece'), ('HU', 'Hungary'), ('IT', 'Italy'), ('KO', 'Kosovo'), ('MA', 'Macedonia'), ('MO', 'Montenegro'), ('RO', 'Romania'), ('SE', 'Serbia'), ('SL', 'Slovenia'), ('TU', 'Turkey')], max_length=2, verbose_name='country 1')),
                ('country2', models.CharField(choices=[('AL', 'Albania'), ('AU', 'Austria'), ('BH', 'Bosnia Herzegovina'), ('BU', 'Bulgaria'), ('CR', 'Croatia'), ('GR', 'Greece'), ('HU', 'Hungary'), ('IT', 'Italy'), ('KO', 'Kosovo'), ('MA', 'Macedonia'), ('MO', 'Montenegro'), ('RO', 'Romania'), ('SE', 'Serbia'), ('SL', 'Slovenia'), ('TU', 'Turkey')], max_length=2, verbose_name='country 2')),
                ('crossingType', models.CharField(blank=True, max_length=200, verbose_name='type')),
                ('lastEditBy', models.CharField(blank=True, max_length=200, verbose_name='last edit by')),
                ('lastUpdate', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('latitude', models.FloatField(blank=True)),
                ('location1', models.CharField(blank=True, max_length=200, verbose_name='location 1')),
                ('location2', models.CharField(blank=True, max_length=200, verbose_name='location 2')),
                ('longitude', models.FloatField(blank=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('notes', models.CharField(blank=True, max_length=4000)),
                ('openingHours', models.CharField(blank=True, max_length=200, verbose_name='opening hours')),
                ('otherNames', models.CharField(blank=True, max_length=2000, verbose_name='other names')),
                ('status', models.TextField(blank=True)),
                ('tcr4Survey', models.BooleanField(verbose_name='TCR4 survey?')),
                ('underEditBy', models.CharField(blank=True, max_length=200, verbose_name='under edit by')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='crossing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crossings.Crossing'),
        ),
    ]
