# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossings', '0002_auto_20160624_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='crossing',
        ),
        migrations.AddField(
            model_name='comment',
            name='crossingId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
