# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossings', '0003_auto_20160705_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crossing',
            name='country1',
        ),
        migrations.RemoveField(
            model_name='crossing',
            name='country2',
        ),
        migrations.RemoveField(
            model_name='crossing',
            name='location1',
        ),
        migrations.RemoveField(
            model_name='crossing',
            name='location2',
        ),
        migrations.AddField(
            model_name='crossing',
            name='countryFrom',
            field=models.CharField(choices=[('AL', 'Albania'), ('AU', 'Austria'), ('BH', 'Bosnia Herzegovina'), ('BU', 'Bulgaria'), ('CR', 'Croatia'), ('GR', 'Greece'), ('HU', 'Hungary'), ('IT', 'Italy'), ('KO', 'Kosovo'), ('MA', 'Macedonia'), ('MO', 'Montenegro'), ('RO', 'Romania'), ('SE', 'Serbia'), ('SL', 'Slovenia'), ('TU', 'Turkey')], default='none', max_length=2, verbose_name='country leaving'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crossing',
            name='countryFromPlace',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='city/town in country being left'),
        ),
        migrations.AddField(
            model_name='crossing',
            name='countryTo',
            field=models.CharField(choices=[('AL', 'Albania'), ('AU', 'Austria'), ('BH', 'Bosnia Herzegovina'), ('BU', 'Bulgaria'), ('CR', 'Croatia'), ('GR', 'Greece'), ('HU', 'Hungary'), ('IT', 'Italy'), ('KO', 'Kosovo'), ('MA', 'Macedonia'), ('MO', 'Montenegro'), ('RO', 'Romania'), ('SE', 'Serbia'), ('SL', 'Slovenia'), ('TU', 'Turkey')], default='none', max_length=2, verbose_name='country entering'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crossing',
            name='countryToPlace',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='city/town in country being entered'),
        ),
    ]
